<?php

namespace PNC\BaseAppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * FichiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichiersRepository extends EntityRepository
{
}
