<?php

namespace PNC\BaseAppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ObservateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservateursRepository extends EntityRepository
{
    public function getLike($like){
        $mgr = $this->getEntityManager();
        $qr = $mgr->createQuery("SELECT o FROM PNCBaseAppBundle:Observateurs o WHERE o.nom_role LIKE '%".$like."%'");
        return $qr->getResult();
    }
}
