<?php

namespace PNC\BaseAppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TaxonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonsRepository extends EntityRepository
{
    public function getLike($like, $ordre){
        $mgr = $this->getEntityManager();
        $like = '%' . strtolower(str_replace(' ', '% ', $like)) . '%';
        $qr = $mgr->createQuery("SELECT o FROM PNCBaseAppBundle:Taxons o WHERE o.ordre=?2 AND o.nom_valide LIKE ?1");
        $qr->setParameter(1, $like);
        $qr->setParameter(2, $ordre);
        return $qr->getResult();
    }
}
