<?php

namespace PNC\BaseAppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ThesaurusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThesaurusRepository extends EntityRepository
{
}
