<?php

namespace PNC\BaseAppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ThesaurusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThesaurusRepository extends EntityRepository
{
    public function getByHierarchy($hierarchy_id){
        $mgr = $this->getEntityManager();
        $qr = $mgr->createQuery("SELECT o FROM PNCBaseAppBundle:Thesaurus o WHERE o.hierarchie LIKE '".$hierarchy_id.".%' order by o.hierarchie ASC");
        return $qr->getResult();
    }
}
