<?php

namespace PNC\ChiroBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ObservateurView
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservateurView extends EntityRepository
{
}
