<?php

namespace PNC\ChiroBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ObservationView
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationView extends EntityRepository
{
}
