<?php

namespace PNC\ChiroBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TaxonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonsRepository extends EntityRepository
{
    public function getLike($like){
        $mgr = $this->getEntityManager();
        $like = strtolower(str_replace(' ', '% ', $like)) . '%';
        $qr = $mgr->createQuery("SELECT o FROM PNCChiroBundle:Taxons o WHERE lower(o.nom_complet) LIKE ?1");
        $qr->setParameter(1, $like);
        return $qr->getResult();
    }
}
