<?php

namespace PNC\PatrimoineBatiBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * InfoSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoSiteRepository extends EntityRepository
{
}
