<?php

namespace PNC\PatrimoineBatiBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * SiteFichiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteFichiersRepository extends EntityRepository
{
}
