<?php

namespace PNC\ExtBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TaxonomieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonomieRepository extends EntityRepository
{
}
